<?php

namespace LaraMake\Console\Commands\Abstracts;

use LaraMake\Console\Commands\Traits\Replace\ReplaceMethodTrait;
use LaraMake\Console\Commands\Traits\Replace\ReplacePropertyTrait;
use LaraMake\Console\Commands\Traits\TemplatesTrait;

abstract class ClassMaker extends PhpMaker
{
    use ReplacePropertyTrait, ReplaceMethodTrait, TemplatesTrait;

    /**
     * @var string
     */
    public $instance = 'class';

    /**
     * @var array
     */
    public $keyWords = [
        'namespace',
        'use',
        'abstract' => 'abstract',
        'pattern',
        'parent',
        'implements',
        'trait',
        'constant',
        'property',
        'method',
    ];

    public $processKeyWordBackSlashParts = [
        'pattern' => 'ucfirst'
    ];

    public $parent;
    protected $__abstract;
    protected $__parent;
    protected $__implements;
    protected $__trait;
    protected $__constant;
    protected $__property;
    protected $__method;

    /**
     * Make BaseTemplate which all templates must be extend
     *
     * @var
     */
    public $makeBase = false;

    /**
     * If basePattern not defined that case basePattern property will automatically created
     *  basePattern = basePrefix .  patternInstance
     *
     * @var string
     */
    public $basePrefix = 'Base';


    /**
     * @var string
     */
    public $stub = 'class.stub';


    /**
     * If has parent basePattern must be extend parent
     * Base pattern name which all class must be extends
     *
     * @var
     */
    public $basePattern;

    /**
     * @param $patterns
     * @param $stubContent
     * @return bool
     */
    public function fillPatterns($patterns, $stubContent)
    {
        if ($this->makeBase) {
            if (false == $this->createBasePattern($stubContent)) {
                // @TODO show dont saved message
                return false;
            }
        }
        return parent::fillPatterns($patterns, $stubContent); // TODO: Change the autogenerated stub
    }

    /**
     * @param $stubContent
     * @return int|null
     */
    public function createBasePattern($stubContent)
    {
        $basePattern = $this->getBasePattern();
        $result = $this->createFileBy($basePattern, $stubContent);

        if ($result) {
            $this->__use = [];
            $this->__implements = [];
            $this->__abstract = false;
            $this->__trait = [];
            $this->__method = [];
            $this->__parent = $this->__namespace . DIRECTORY_SEPARATOR . $basePattern;
        }

        return $result;
    }

    public function getBasePatternFullName()
    {
        return $this->getRelativePath() . $this->getBasePattern();
    }

    /**
     * @return string
     */
    public function getBasePattern()
    {
        if ($this->basePattern) {
            return $this->basePattern;
        }

        return ucfirst($this->basePrefix) . ucfirst($this->instance);
    }

    /**
     * @param $content
     * @param $keyWord
     * @param $input
     * @return mixed
     */
    public function replaceAbstractKeyWord($content, $keyWord, $input)
    {
        if (true == $input) {
            return str_replace($keyWord, 'abstract', $content);
        }
        return str_replace($keyWord . ' ', '', $content);
    }

    /**
     * @param $content
     * @param $keyWord
     * @param $input
     * @return mixed
     */
    public function replacePatternKeyWord($content, $keyWord, $input)
    {
        if (strpos($input, DIRECTORY_SEPARATOR)) {
            $input = last(explode(DIRECTORY_SEPARATOR, $input));
        }

        return str_replace($keyWord, $input, $content);
    }

    /**
     * @param $content
     * @param $keyWord
     * @param $input
     * @return mixed
     */
    public function replaceParentKeyWord($content, $keyWord, $input)
    {
        $parent = $input ?? $this->parent;
        if (empty($parent)) {
            return str_replace(' ' . $keyWord, '', $content);
        }

        $baseName = $this->getNamespaceBaseName($parent, $this->__use);
        $to = sprintf('extends %s', $baseName);
        return str_replace($keyWord, $to, $content);
    }

    /**
     * @param $content
     * @param $keyWord
     * @param $input
     * @return mixed
     */
    public function replaceImplementsKeyWord($content, $keyWord, $input)
    {
        if (empty($input)) {
            return str_replace(' ' . $keyWord, '', $content);
        }

        $input = (array) $input;
        $interfaces = [];
        foreach ($input as $interface) {
            $interfaces[] = $this->getNamespaceBaseName($interface, $this->__use);
        }

        $to = sprintf('implements %s', implode(', ', $interfaces));
        return str_replace($keyWord, $to, $content);

    }

    /**
     * @param $content
     * @param $keyWord
     * @param $input
     * @return mixed
     */
    public function replaceTraitKeyWord($content, $keyWord, $input)
    {
        if (empty($input)) {
            return str_replace(PHP_EOL .TAB . $keyWord . PHP_EOL, '', $content);
        }

        $input = (array) $input;
        $traits = [];
        foreach ($input as $trait) {
            $traits[] = $this->getNamespaceBaseName($trait, $this->__use);
        }

        $to = sprintf('use %s;', implode(', ', $traits));
        return str_replace($keyWord, $to, $content);
    }

    /**
     * @param $content
     * @param $keyWord
     * @param $input
     * @return mixed
     */
    public function replaceConstantKeyWord($content, $keyWord, $input)
    {
        $input = (array) $input;
        // @TODO generalize it and processInputIsArray check in dynamicallyParseOptionInput

        $str = '';
        foreach ($input as $constant => $value) {
        // @TODO fix
            $template = $this->parser->parseAttribute($constant, $value, '=', ';', 2);
            $template = str_replace_first('$', '', $template);
            $template = 'const ' . $template .PHP_EOL . PHP_EOL . TAB;
            $str .= $template;
        }

        if (empty($str)) {
            return str_replace(PHP_EOL .TAB . $keyWord . PHP_EOL, '', $content);
        }

        $str = rtrim($str, PHP_EOL . PHP_EOL . TAB);

        return str_replace($keyWord , $str, $content);
    }

    public function trimUseKeyWord($content, $keyWord)
    {
        return parent::trimUseKeyWord($content, $keyWord); // TODO: Change the autogenerated stub
    }

    public function trimFinalContent($content)
    {
        $content = str_replace_last(PHP_EOL . '{}'. PHP_EOL, PHP_EOL . '{' . PHP_EOL . TAB . PHP_EOL . '}'. PHP_EOL, $content);
        return parent::trimFinalContent($content);
    }
}
